language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: build
      script: ./gradlew build -s -x jvmTest -x jsIrTest -x jsIrBrowserTest -x jsIrNodeTest -x jsLegacyTest -x jsLegacyBrowserTest -x jsLegacyNodeTest
    - state: test
      script: ./gradlew allTests
    - state: dokka
      script: ./gradlew dokkaHtml
